### ISSUE TITLE
Deeplink to Jitsi App

### ISSUE THREAD

**Issue by githubtobi** [nextcloud/jitsi#8]
Hi there,

would it be possible to add a second button "join with app" into the jitsi app under point (2) in the menu "join with jitsi app"?

The link under the button would then be: jitsi-meet://<servername>

If the app is installed, it will open the jitsi app in the selected room. No copy/paste is required.

**Comment by t-lo** [comment]
+1 for this proposal! It seems like a rather low-hanging fruit: just use the room link the page already generates but replace `https://` with `jitsi-meet://`.
Right now in order to use the Android app I have to:

1. Open nextcloud in a browser, navigate to the "Meetings" page, and prepare entering a room
2. Generate a link and copy to clipboard
3. Open the mail app and draft an email to myself
4. Paste the link, replace `https://` with `jitsi-meet://`, save the draft
5. Open the draft email in read mode (so the link is rendered), tap the link (which now starts the app)
6. Profit

Please help making this workflow less horrible.

**Comment by weeman1337** [comment]
This would be a nice task for Hacktoberfest.

I would would suggest to re-work the „Join with Jitsi app“ section like this:

- At the bottom add a button „Join using the Jitsi app“
- This button would generate the link on click and then open the URL
- Keep the current expandable section and rename it to „More info about this“ with the contents

1. Download the app here
2. Click here to join (same button as above)
3. Does not work?
4. Create participation link
5. Paste the link from above into the input field on the App start screen

**Comment by t-lo** [comment]
@weeman1337 Took a stab at it here: https://github.com/nextcloud/jitsi/pull/12 Not sure I got it right, I'm usually concerned with OS / kernel /n plumbing level stuff :) Feedback very welcome.
